// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ItemUuid         uuid.UUID      `json:"item_uuid"`
	Price            pgtype.Numeric `json:"price"`
	ShortDescription pgtype.Text    `json:"short_description"`
}

type Receipt struct {
	ReceiptUuid  uuid.UUID      `json:"receipt_uuid"`
	Total        pgtype.Numeric `json:"total"`
	PurchaseDate pgtype.Date    `json:"purchase_date"`
	PurchaseTime pgtype.Time    `json:"purchase_time"`
	Retailer     string         `json:"retailer"`
}

type ReceiptItem struct {
	ItemUuid    uuid.UUID `json:"item_uuid"`
	ReceiptUuid uuid.UUID `json:"receipt_uuid"`
}
