// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipt
(total,  purchase_time, retailer)
VALUES(
    $1, $2, $3
)
RETURNING receipt_uuid
`

type CreateReceiptParams struct {
	Total        float64   `json:"total"`
	PurchaseTime time.Time `json:"purchase_time"`
	Retailer     string    `json:"retailer"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createReceipt, arg.Total, arg.PurchaseTime, arg.Retailer)
	var receipt_uuid uuid.UUID
	err := row.Scan(&receipt_uuid)
	return receipt_uuid, err
}

const getItemsByReceipt = `-- name: GetItemsByReceipt :many
SELECT i.item_uuid, i.price, i.short_description
FROM receipt_items ri, item i
WHERE ri.item_uuid = i.item_uuid
AND ri.receipt_uuid = $1
`

func (q *Queries) GetItemsByReceipt(ctx context.Context, receiptUuid uuid.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItemsByReceipt, receiptUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ItemUuid, &i.Price, &i.ShortDescription); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReceiptById = `-- name: GetReceiptById :one
SELECT receipt_uuid, total, purchase_time, retailer
FROM receipt
WHERE receipt_uuid = $1
`

type GetReceiptByIdRow struct {
	ReceiptUuid  uuid.UUID `json:"receipt_uuid"`
	Total        float64   `json:"total"`
	PurchaseTime time.Time `json:"purchase_time"`
	Retailer     string    `json:"retailer"`
}

func (q *Queries) GetReceiptById(ctx context.Context, receiptUuid uuid.UUID) (GetReceiptByIdRow, error) {
	row := q.db.QueryRow(ctx, getReceiptById, receiptUuid)
	var i GetReceiptByIdRow
	err := row.Scan(
		&i.ReceiptUuid,
		&i.Total,
		&i.PurchaseTime,
		&i.Retailer,
	)
	return i, err
}
